# Generated by Django 3.2.5 on 2021-07-30 14:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('NewsApp', '0002_sportnews'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2021, 7, 30, 14, 57, 35, 887313, tzinfo=utc)),
        ),
    ]
